### ISSUE TITLE
Corrección 20-03-2024 1.0

### ISSUE THREAD

**Issue by monkeyjp** [Martharoca/List_with_fetch#1]
Marta, al ejercicio le esta faltando la funcionalidad para agregar tareas y eliminarlas en el API. hasta ahora solo lo estas haciendo localmente pero si das refresh a la pagina, el agregar una tarea o eliminarla no se guarda. 
te dejo algunas lineas de código que pudieran solucionar esto. chequealas y cualquier duda me preguntas.
![Screenshot 2024-03-20 at 09 32 35](https://github.com/Martharoca/List_with_fetch/assets/43521145/3851694b-766b-485c-b3d5-6a39a94188a7)
![Screenshot 2024-03-20 at 09 34 17](https://github.com/Martharoca/List_with_fetch/assets/43521145/8c6a5508-bcc1-48fa-a917-84fa44599c8b)
![Screenshot 2024-03-20 at 09 35 51](https://github.com/Martharoca/List_with_fetch/assets/43521145/42f97316-90c5-4793-963a-45aa44f9796d)

**Comment by Martharoca** [comment]
muchas gracias Javier! y perdona la tardanza que he tenido mucha tarea en el curro.
Ahora mismo miro el código y lo corrijo, sabía que no estaba bien pero es que ya me estaba desesperando y no quería atrasar más la entrega. 
He vuelto a hacer el Practice de React porque había conceptos que no tenía muy claros aún y creo que ya me defiendo (más o menos) si tras la clase de mañana veo que me surgen demasiadas dudas ya sí te pediré tutoría para la próxima semana.
